app = 'flyvpn'
primary_region = 'den'

[[services]]
  protocol = 'tcp'
  internal_port = 5555
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[services.ports]]
    port = 5555

[[services]]
  protocol = 'tcp'
  internal_port = 992

  [[services.ports]]
    port = 992

[[services]]
  protocol = 'tcp'
  internal_port = 443

  [[services.ports]]
    port = 443

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "backup"
  destination = "/var/opt/backup"
