echo "This is the Fly VPN command line interface."
echo
echo "Usage:"
echo "  nix run"
echo "  └ Alias for .#help"
echo "  nix run .#help"
echo "  └ Print this helpful information"
echo "  nix run .#start"
echo "  └ Alias for .#start native"
echo "  nix run .#start native"
echo "  └ Start the server natively on your machine"
echo "  nix run .#start container"
echo "  └ Start the server in a container on your machine"
echo "  nix develop"
echo "  └ Start a dev shell with all project dependencies installed"
